version: '3.8'

services:
  isee-be:
    image: ghcr.io/ditjen-dikti-kemdikbud-ri/iss-be:{environment}
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
