name: Deploy to Staging (Main Branch I mean, since it's just for learning purposes)
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "docker-compose.yaml"
          target: "~/iss-be/"
          overwrite: true

      - name: Build on server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/iss-be/
            if [ -f .env ]; then
              rm .env
            fi
            touch .env
            printf "APP_ENV=staging\n" >> .env
            printf "SERVER_PORT=%s\n" "${{ secrets.SERVER_PORT }}" >> .env
            printf "DB_URI=\"%s\"\n" "${{ secrets.DB_URI }}" >> .env
            printf "DB_NAME=%s\n" "${{ secrets.DB_NAME }}" >> .env
            docker compose pull
            docker compose up -d --remove-orphans --build